spring:
  application:
    name: javaverse

  datasource:
    url: jdbc:postgresql://db:5432/tasks
    username: myuser
    password: mypassword
    driver-class-name: "org.postgresql.Driver"

  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 5190
